/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueroSaberMaisRouteImport } from './routes/quero-saber-mais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedClienteRoiRouteImport } from './routes/_authenticated/cliente/roi'
import { Route as AuthenticatedClienteMetaAdsRouteImport } from './routes/_authenticated/cliente/meta-ads'
import { Route as AuthenticatedClienteLeadsRouteImport } from './routes/_authenticated/cliente/leads'
import { Route as AuthenticatedClienteEntregasRouteImport } from './routes/_authenticated/cliente/entregas'
import { Route as AuthenticatedClienteDiagnosticoRouteImport } from './routes/_authenticated/cliente/diagnostico'
import { Route as AuthenticatedClienteDashboardRouteImport } from './routes/_authenticated/cliente/dashboard'
import { Route as AuthenticatedClienteConteudoRouteImport } from './routes/_authenticated/cliente/conteudo'
import { Route as AuthenticatedClienteConexoesRouteImport } from './routes/_authenticated/cliente/conexoes'
import { Route as AuthenticatedClienteClientesRouteImport } from './routes/_authenticated/cliente/clientes'
import { Route as AuthenticatedClienteCalendarioRouteImport } from './routes/_authenticated/cliente/calendario'
import { Route as AuthenticatedClienteAtendimentoRouteImport } from './routes/_authenticated/cliente/atendimento'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminRoiRouteImport } from './routes/_authenticated/admin/roi'
import { Route as AuthenticatedAdminMetaAdsRouteImport } from './routes/_authenticated/admin/meta-ads'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminEstrategiaRouteImport } from './routes/_authenticated/admin/estrategia'
import { Route as AuthenticatedAdminDiagnosticosRouteImport } from './routes/_authenticated/admin/diagnosticos'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminConfigMetaRouteImport } from './routes/_authenticated/admin/config-meta'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin/calendario'
import { Route as AuthenticatedAdminAutomacoesLeadsRouteImport } from './routes/_authenticated/admin/automacoes-leads'
import { Route as AuthenticatedAdminAtendimentoRouteImport } from './routes/_authenticated/admin/atendimento'
import { Route as AuthenticatedAdminClientesIndexRouteImport } from './routes/_authenticated/admin/clientes/index'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin/clientes/$id'

const QueroSaberMaisRoute = QueroSaberMaisRouteImport.update({
  id: '/quero-saber-mais',
  path: '/quero-saber-mais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClienteRoiRoute = AuthenticatedClienteRoiRouteImport.update({
  id: '/cliente/roi',
  path: '/cliente/roi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteMetaAdsRoute =
  AuthenticatedClienteMetaAdsRouteImport.update({
    id: '/cliente/meta-ads',
    path: '/cliente/meta-ads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteLeadsRoute =
  AuthenticatedClienteLeadsRouteImport.update({
    id: '/cliente/leads',
    path: '/cliente/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteEntregasRoute =
  AuthenticatedClienteEntregasRouteImport.update({
    id: '/cliente/entregas',
    path: '/cliente/entregas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteDiagnosticoRoute =
  AuthenticatedClienteDiagnosticoRouteImport.update({
    id: '/cliente/diagnostico',
    path: '/cliente/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteDashboardRoute =
  AuthenticatedClienteDashboardRouteImport.update({
    id: '/cliente/dashboard',
    path: '/cliente/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteConteudoRoute =
  AuthenticatedClienteConteudoRouteImport.update({
    id: '/cliente/conteudo',
    path: '/cliente/conteudo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteConexoesRoute =
  AuthenticatedClienteConexoesRouteImport.update({
    id: '/cliente/conexoes',
    path: '/cliente/conexoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteClientesRoute =
  AuthenticatedClienteClientesRouteImport.update({
    id: '/cliente/clientes',
    path: '/cliente/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteCalendarioRoute =
  AuthenticatedClienteCalendarioRouteImport.update({
    id: '/cliente/calendario',
    path: '/cliente/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteAtendimentoRoute =
  AuthenticatedClienteAtendimentoRouteImport.update({
    id: '/cliente/atendimento',
    path: '/cliente/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoiRoute = AuthenticatedAdminRoiRouteImport.update({
  id: '/admin/roi',
  path: '/admin/roi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMetaAdsRoute =
  AuthenticatedAdminMetaAdsRouteImport.update({
    id: '/admin/meta-ads',
    path: '/admin/meta-ads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEstrategiaRoute =
  AuthenticatedAdminEstrategiaRouteImport.update({
    id: '/admin/estrategia',
    path: '/admin/estrategia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDiagnosticosRoute =
  AuthenticatedAdminDiagnosticosRouteImport.update({
    id: '/admin/diagnosticos',
    path: '/admin/diagnosticos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfigMetaRoute =
  AuthenticatedAdminConfigMetaRouteImport.update({
    id: '/admin/config-meta',
    path: '/admin/config-meta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/admin/calendario',
    path: '/admin/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAutomacoesLeadsRoute =
  AuthenticatedAdminAutomacoesLeadsRouteImport.update({
    id: '/admin/automacoes-leads',
    path: '/admin/automacoes-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAtendimentoRoute =
  AuthenticatedAdminAtendimentoRouteImport.update({
    id: '/admin/atendimento',
    path: '/admin/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientesIndexRoute =
  AuthenticatedAdminClientesIndexRouteImport.update({
    id: '/admin/clientes/',
    path: '/admin/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/admin/clientes/$id',
    path: '/admin/clientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quero-saber-mais': typeof QueroSaberMaisRoute
  '/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/admin/automacoes-leads': typeof AuthenticatedAdminAutomacoesLeadsRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/config-meta': typeof AuthenticatedAdminConfigMetaRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/estrategia': typeof AuthenticatedAdminEstrategiaRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/meta-ads': typeof AuthenticatedAdminMetaAdsRoute
  '/admin/roi': typeof AuthenticatedAdminRoiRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/atendimento': typeof AuthenticatedClienteAtendimentoRoute
  '/cliente/calendario': typeof AuthenticatedClienteCalendarioRoute
  '/cliente/clientes': typeof AuthenticatedClienteClientesRoute
  '/cliente/conexoes': typeof AuthenticatedClienteConexoesRoute
  '/cliente/conteudo': typeof AuthenticatedClienteConteudoRoute
  '/cliente/dashboard': typeof AuthenticatedClienteDashboardRoute
  '/cliente/diagnostico': typeof AuthenticatedClienteDiagnosticoRoute
  '/cliente/entregas': typeof AuthenticatedClienteEntregasRoute
  '/cliente/leads': typeof AuthenticatedClienteLeadsRoute
  '/cliente/meta-ads': typeof AuthenticatedClienteMetaAdsRoute
  '/cliente/roi': typeof AuthenticatedClienteRoiRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quero-saber-mais': typeof QueroSaberMaisRoute
  '/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/admin/automacoes-leads': typeof AuthenticatedAdminAutomacoesLeadsRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/config-meta': typeof AuthenticatedAdminConfigMetaRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/estrategia': typeof AuthenticatedAdminEstrategiaRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/meta-ads': typeof AuthenticatedAdminMetaAdsRoute
  '/admin/roi': typeof AuthenticatedAdminRoiRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/atendimento': typeof AuthenticatedClienteAtendimentoRoute
  '/cliente/calendario': typeof AuthenticatedClienteCalendarioRoute
  '/cliente/clientes': typeof AuthenticatedClienteClientesRoute
  '/cliente/conexoes': typeof AuthenticatedClienteConexoesRoute
  '/cliente/conteudo': typeof AuthenticatedClienteConteudoRoute
  '/cliente/dashboard': typeof AuthenticatedClienteDashboardRoute
  '/cliente/diagnostico': typeof AuthenticatedClienteDiagnosticoRoute
  '/cliente/entregas': typeof AuthenticatedClienteEntregasRoute
  '/cliente/leads': typeof AuthenticatedClienteLeadsRoute
  '/cliente/meta-ads': typeof AuthenticatedClienteMetaAdsRoute
  '/cliente/roi': typeof AuthenticatedClienteRoiRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/quero-saber-mais': typeof QueroSaberMaisRoute
  '/_authenticated/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/_authenticated/admin/automacoes-leads': typeof AuthenticatedAdminAutomacoesLeadsRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/config-meta': typeof AuthenticatedAdminConfigMetaRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/_authenticated/admin/estrategia': typeof AuthenticatedAdminEstrategiaRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/meta-ads': typeof AuthenticatedAdminMetaAdsRoute
  '/_authenticated/admin/roi': typeof AuthenticatedAdminRoiRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/cliente/atendimento': typeof AuthenticatedClienteAtendimentoRoute
  '/_authenticated/cliente/calendario': typeof AuthenticatedClienteCalendarioRoute
  '/_authenticated/cliente/clientes': typeof AuthenticatedClienteClientesRoute
  '/_authenticated/cliente/conexoes': typeof AuthenticatedClienteConexoesRoute
  '/_authenticated/cliente/conteudo': typeof AuthenticatedClienteConteudoRoute
  '/_authenticated/cliente/dashboard': typeof AuthenticatedClienteDashboardRoute
  '/_authenticated/cliente/diagnostico': typeof AuthenticatedClienteDiagnosticoRoute
  '/_authenticated/cliente/entregas': typeof AuthenticatedClienteEntregasRoute
  '/_authenticated/cliente/leads': typeof AuthenticatedClienteLeadsRoute
  '/_authenticated/cliente/meta-ads': typeof AuthenticatedClienteMetaAdsRoute
  '/_authenticated/cliente/roi': typeof AuthenticatedClienteRoiRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/_authenticated/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/quero-saber-mais'
    | '/admin/atendimento'
    | '/admin/automacoes-leads'
    | '/admin/calendario'
    | '/admin/config-meta'
    | '/admin/dashboard'
    | '/admin/diagnosticos'
    | '/admin/estrategia'
    | '/admin/leads'
    | '/admin/meta-ads'
    | '/admin/roi'
    | '/admin/usuarios'
    | '/cliente/atendimento'
    | '/cliente/calendario'
    | '/cliente/clientes'
    | '/cliente/conexoes'
    | '/cliente/conteudo'
    | '/cliente/dashboard'
    | '/cliente/diagnostico'
    | '/cliente/entregas'
    | '/cliente/leads'
    | '/cliente/meta-ads'
    | '/cliente/roi'
    | '/admin/clientes/$id'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/quero-saber-mais'
    | '/admin/atendimento'
    | '/admin/automacoes-leads'
    | '/admin/calendario'
    | '/admin/config-meta'
    | '/admin/dashboard'
    | '/admin/diagnosticos'
    | '/admin/estrategia'
    | '/admin/leads'
    | '/admin/meta-ads'
    | '/admin/roi'
    | '/admin/usuarios'
    | '/cliente/atendimento'
    | '/cliente/calendario'
    | '/cliente/clientes'
    | '/cliente/conexoes'
    | '/cliente/conteudo'
    | '/cliente/dashboard'
    | '/cliente/diagnostico'
    | '/cliente/entregas'
    | '/cliente/leads'
    | '/cliente/meta-ads'
    | '/cliente/roi'
    | '/admin/clientes/$id'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/quero-saber-mais'
    | '/_authenticated/admin/atendimento'
    | '/_authenticated/admin/automacoes-leads'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/config-meta'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/diagnosticos'
    | '/_authenticated/admin/estrategia'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/meta-ads'
    | '/_authenticated/admin/roi'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/cliente/atendimento'
    | '/_authenticated/cliente/calendario'
    | '/_authenticated/cliente/clientes'
    | '/_authenticated/cliente/conexoes'
    | '/_authenticated/cliente/conteudo'
    | '/_authenticated/cliente/dashboard'
    | '/_authenticated/cliente/diagnostico'
    | '/_authenticated/cliente/entregas'
    | '/_authenticated/cliente/leads'
    | '/_authenticated/cliente/meta-ads'
    | '/_authenticated/cliente/roi'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  QueroSaberMaisRoute: typeof QueroSaberMaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quero-saber-mais': {
      id: '/quero-saber-mais'
      path: '/quero-saber-mais'
      fullPath: '/quero-saber-mais'
      preLoaderRoute: typeof QueroSaberMaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cliente/roi': {
      id: '/_authenticated/cliente/roi'
      path: '/cliente/roi'
      fullPath: '/cliente/roi'
      preLoaderRoute: typeof AuthenticatedClienteRoiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/meta-ads': {
      id: '/_authenticated/cliente/meta-ads'
      path: '/cliente/meta-ads'
      fullPath: '/cliente/meta-ads'
      preLoaderRoute: typeof AuthenticatedClienteMetaAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/leads': {
      id: '/_authenticated/cliente/leads'
      path: '/cliente/leads'
      fullPath: '/cliente/leads'
      preLoaderRoute: typeof AuthenticatedClienteLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/entregas': {
      id: '/_authenticated/cliente/entregas'
      path: '/cliente/entregas'
      fullPath: '/cliente/entregas'
      preLoaderRoute: typeof AuthenticatedClienteEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/diagnostico': {
      id: '/_authenticated/cliente/diagnostico'
      path: '/cliente/diagnostico'
      fullPath: '/cliente/diagnostico'
      preLoaderRoute: typeof AuthenticatedClienteDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/dashboard': {
      id: '/_authenticated/cliente/dashboard'
      path: '/cliente/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof AuthenticatedClienteDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/conteudo': {
      id: '/_authenticated/cliente/conteudo'
      path: '/cliente/conteudo'
      fullPath: '/cliente/conteudo'
      preLoaderRoute: typeof AuthenticatedClienteConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/conexoes': {
      id: '/_authenticated/cliente/conexoes'
      path: '/cliente/conexoes'
      fullPath: '/cliente/conexoes'
      preLoaderRoute: typeof AuthenticatedClienteConexoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/clientes': {
      id: '/_authenticated/cliente/clientes'
      path: '/cliente/clientes'
      fullPath: '/cliente/clientes'
      preLoaderRoute: typeof AuthenticatedClienteClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/calendario': {
      id: '/_authenticated/cliente/calendario'
      path: '/cliente/calendario'
      fullPath: '/cliente/calendario'
      preLoaderRoute: typeof AuthenticatedClienteCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/atendimento': {
      id: '/_authenticated/cliente/atendimento'
      path: '/cliente/atendimento'
      fullPath: '/cliente/atendimento'
      preLoaderRoute: typeof AuthenticatedClienteAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roi': {
      id: '/_authenticated/admin/roi'
      path: '/admin/roi'
      fullPath: '/admin/roi'
      preLoaderRoute: typeof AuthenticatedAdminRoiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/meta-ads': {
      id: '/_authenticated/admin/meta-ads'
      path: '/admin/meta-ads'
      fullPath: '/admin/meta-ads'
      preLoaderRoute: typeof AuthenticatedAdminMetaAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/estrategia': {
      id: '/_authenticated/admin/estrategia'
      path: '/admin/estrategia'
      fullPath: '/admin/estrategia'
      preLoaderRoute: typeof AuthenticatedAdminEstrategiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/diagnosticos': {
      id: '/_authenticated/admin/diagnosticos'
      path: '/admin/diagnosticos'
      fullPath: '/admin/diagnosticos'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/config-meta': {
      id: '/_authenticated/admin/config-meta'
      path: '/admin/config-meta'
      fullPath: '/admin/config-meta'
      preLoaderRoute: typeof AuthenticatedAdminConfigMetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/admin/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/automacoes-leads': {
      id: '/_authenticated/admin/automacoes-leads'
      path: '/admin/automacoes-leads'
      fullPath: '/admin/automacoes-leads'
      preLoaderRoute: typeof AuthenticatedAdminAutomacoesLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/atendimento': {
      id: '/_authenticated/admin/atendimento'
      path: '/admin/atendimento'
      fullPath: '/admin/atendimento'
      preLoaderRoute: typeof AuthenticatedAdminAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clientes/': {
      id: '/_authenticated/admin/clientes/'
      path: '/admin/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AuthenticatedAdminClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/admin/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAtendimentoRoute: typeof AuthenticatedAdminAtendimentoRoute
  AuthenticatedAdminAutomacoesLeadsRoute: typeof AuthenticatedAdminAutomacoesLeadsRoute
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminConfigMetaRoute: typeof AuthenticatedAdminConfigMetaRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDiagnosticosRoute: typeof AuthenticatedAdminDiagnosticosRoute
  AuthenticatedAdminEstrategiaRoute: typeof AuthenticatedAdminEstrategiaRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMetaAdsRoute: typeof AuthenticatedAdminMetaAdsRoute
  AuthenticatedAdminRoiRoute: typeof AuthenticatedAdminRoiRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedClienteAtendimentoRoute: typeof AuthenticatedClienteAtendimentoRoute
  AuthenticatedClienteCalendarioRoute: typeof AuthenticatedClienteCalendarioRoute
  AuthenticatedClienteClientesRoute: typeof AuthenticatedClienteClientesRoute
  AuthenticatedClienteConexoesRoute: typeof AuthenticatedClienteConexoesRoute
  AuthenticatedClienteConteudoRoute: typeof AuthenticatedClienteConteudoRoute
  AuthenticatedClienteDashboardRoute: typeof AuthenticatedClienteDashboardRoute
  AuthenticatedClienteDiagnosticoRoute: typeof AuthenticatedClienteDiagnosticoRoute
  AuthenticatedClienteEntregasRoute: typeof AuthenticatedClienteEntregasRoute
  AuthenticatedClienteLeadsRoute: typeof AuthenticatedClienteLeadsRoute
  AuthenticatedClienteMetaAdsRoute: typeof AuthenticatedClienteMetaAdsRoute
  AuthenticatedClienteRoiRoute: typeof AuthenticatedClienteRoiRoute
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRoute
  AuthenticatedAdminClientesIndexRoute: typeof AuthenticatedAdminClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAtendimentoRoute: AuthenticatedAdminAtendimentoRoute,
  AuthenticatedAdminAutomacoesLeadsRoute:
    AuthenticatedAdminAutomacoesLeadsRoute,
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminConfigMetaRoute: AuthenticatedAdminConfigMetaRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDiagnosticosRoute: AuthenticatedAdminDiagnosticosRoute,
  AuthenticatedAdminEstrategiaRoute: AuthenticatedAdminEstrategiaRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMetaAdsRoute: AuthenticatedAdminMetaAdsRoute,
  AuthenticatedAdminRoiRoute: AuthenticatedAdminRoiRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedClienteAtendimentoRoute: AuthenticatedClienteAtendimentoRoute,
  AuthenticatedClienteCalendarioRoute: AuthenticatedClienteCalendarioRoute,
  AuthenticatedClienteClientesRoute: AuthenticatedClienteClientesRoute,
  AuthenticatedClienteConexoesRoute: AuthenticatedClienteConexoesRoute,
  AuthenticatedClienteConteudoRoute: AuthenticatedClienteConteudoRoute,
  AuthenticatedClienteDashboardRoute: AuthenticatedClienteDashboardRoute,
  AuthenticatedClienteDiagnosticoRoute: AuthenticatedClienteDiagnosticoRoute,
  AuthenticatedClienteEntregasRoute: AuthenticatedClienteEntregasRoute,
  AuthenticatedClienteLeadsRoute: AuthenticatedClienteLeadsRoute,
  AuthenticatedClienteMetaAdsRoute: AuthenticatedClienteMetaAdsRoute,
  AuthenticatedClienteRoiRoute: AuthenticatedClienteRoiRoute,
  AuthenticatedAdminClientesIdRoute: AuthenticatedAdminClientesIdRoute,
  AuthenticatedAdminClientesIndexRoute: AuthenticatedAdminClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  QueroSaberMaisRoute: QueroSaberMaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
